package org.ual.hmis.hmislovers;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class CrearbarTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    int browser = 0; // 0: firefox, 1: chrome
    boolean headless = true;

    switch (browser) {
      case 0:  // Firefox
        org.openqa.selenium.firefox.FirefoxOptions firefoxOptions = new org.openqa.selenium.firefox.FirefoxOptions();
        if (headless) {
          firefoxOptions.addArguments("--headless");
        }
        driver = new org.openqa.selenium.firefox.FirefoxDriver(firefoxOptions);
        break;

      case 1: // Chrome
        org.openqa.selenium.chrome.ChromeOptions chromeOptions = new org.openqa.selenium.chrome.ChromeOptions();
        if (headless) {
          chromeOptions.addArguments("--headless=new");
        }
        chromeOptions.addArguments("--start-maximized"); 
        chromeOptions.addArguments("window-size=1920,1080");
        
        driver = new org.openqa.selenium.chrome.ChromeDriver(chromeOptions);
        break;

      default:
        fail("Please select a browser");
        break;
    }

    driver.manage().timeouts().implicitlyWait(java.time.Duration.ofSeconds(5));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  @Test
  public void crearbar() {
    // Generación dinámica única para evitar colisiones en la DB remota
    String sufijoAleatorio = UUID.randomUUID().toString().substring(0, 6);
    String nombreNuevoBar = "casa angel " + sufijoAleatorio;

    driver.get("https://calm-moss-09572aa03.7.azurestaticapps.net/");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    
    WebDriverWait wait = new WebDriverWait(driver, java.time.Duration.ofSeconds(15));
    WebDriverWait waitLargo = new WebDriverWait(driver, java.time.Duration.ofSeconds(30));

    // Login previo
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("login-username"))).sendKeys("admin");
    driver.findElement(By.id("login-password")).sendKeys("1234");
    driver.findElement(By.cssSelector(".btn-auth-submit")).click();

    // Crear el nuevo bar
    WebElement btnAddBar = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-add-bar")));
    btnAddBar.click();

    WebElement inputBarName = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("new-bar-name")));
    inputBarName.click();
    inputBarName.sendKeys(nombreNuevoBar);

    driver.findElement(By.id("new-bar-dir")).click();
    driver.findElement(By.id("new-bar-dir")).sendKeys("calle nueva 123");

    driver.findElement(By.cssSelector(".btn-submit-bar")).click();

    // Esperar a que el modal overlay de creación desaparezca por completo
    wait.until(ExpectedConditions.invisibilityOfElementLocated(By.id("new-bar-name")));
    
    // Forzar refresco ligero o pequeña pausa para garantizar sincronía en Firefox Headless
    try { Thread.sleep(1000); } catch (Exception e) {}
    driver.navigate().refresh();

    // Validar de forma dinámica que el bar aparece correctamente en la vista
    WebElement tarjetaCreada = waitLargo.until(
        ExpectedConditions.visibilityOfElementLocated(By.xpath("//h3[contains(text(), '" + nombreNuevoBar + "')]"))
    );
    
    js.executeScript("arguments[0].scrollIntoView({block: 'center'});", tarjetaCreada);
    
    // Aserción final del texto de la tarjeta
    assertTrue(tarjetaCreada.isDisplayed());
    assertThat(tarjetaCreada.getText(), is(nombreNuevoBar));
  }
}