package org.ual.hmis.hmislovers;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class CrearNuevoUsuarioIncorrectoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    // Browser selector
    int browser = 0; // 0: firefox, 1: chrome
    boolean headless = false; // Cambiado a 'boolean' primitivo por buena práctica

    switch (browser) {
      case 0:  // Firefox
        // NOTA: Si usas Selenium 4.11 o superior, puedes comentar la línea de abajo 
        // y Selenium descargará el driver solo sin necesidad de la carpeta drivers/
        System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe");
        
        org.openqa.selenium.firefox.FirefoxOptions firefoxOptions = new org.openqa.selenium.firefox.FirefoxOptions();
        if (headless) {
          firefoxOptions.addArguments("--headless");
        }
        driver = new org.openqa.selenium.firefox.FirefoxDriver(firefoxOptions);
        break;

      case 1: // Chrome
        System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
        
        org.openqa.selenium.chrome.ChromeOptions chromeOptions = new org.openqa.selenium.chrome.ChromeOptions();
        if (headless) {
          chromeOptions.addArguments("--headless=new");
        }
        // Forzamos a Chrome a abrirse grande para que no falle ningún selector por temas de maquetación responsive
        chromeOptions.addArguments("--start-maximized"); 
        chromeOptions.addArguments("window-size=1920,1080");
        
        driver = new org.openqa.selenium.chrome.ChromeDriver(chromeOptions);
        break;

      default:
        fail("Please select a browser");
        break;
    }

    // Sincronización base para la suite
    driver.manage().timeouts().implicitlyWait(java.time.Duration.ofSeconds(5));
    
    // Garantizamos el maximizado físico de la ventana si el modo no es headless
    if (!headless) {
      driver.manage().window().maximize();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void crearNuevoUsuarioIncorrecto() {
    // 1 | open | Vamos a la raíz de la aplicación
    driver.get("http://localhost:5173/");
    // Maximizamos para garantizar que se renderice el diseño de escritorio completo
    driver.manage().window().maximize();
    
    WebDriverWait wait = new WebDriverWait(driver, java.time.Duration.ofSeconds(10));

    // ===================================================
    // BLOQUE OBLIGATORIO: INICIAR SESIÓN COMO ADMINISTRADOR
    // ===================================================
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("login-username"))).sendKeys("admin");
    driver.findElement(By.id("login-password")).sendKeys("1234");
    driver.findElement(By.cssSelector(".btn-auth-submit")).click();
    // ===================================================

    // 3 | click | Hacemos clic en el botón de administración de la barra superior
    WebElement btnAdmin = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-admin-header > .material-icons")));
    btnAdmin.click();

    // 4 | click | Hacemos clic en el botón para añadir un nuevo usuario
    WebElement btnAdd = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-admin-add")));
    btnAdd.click();

    // 5 | click | Seleccionamos el campo de email (esperando a que el formulario sea visible)
    WebElement inputEmail = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("admin-new-email")));
    inputEmail.click();

    // 6 | type | Rellenamos un email
    inputEmail.sendKeys("awda@adwa.es");

    // 7 | type | Rellenamos una contraseña (dejando vacío el nombre de usuario de forma deliberada)
    driver.findElement(By.id("admin-new-password")).sendKeys("awdADW");

    // 8 | click | Intentamos enviar el formulario incompleto pulsando en guardar
    driver.findElement(By.cssSelector(".btn-submit-bar")).click();

    // 9 y 10 | assertText | Verificamos que el sistema no avanza (falla el guardado) y nos mantiene en el título h3 esperado
    WebElement encabezado = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("h3")));
    encabezado.click();
    
    assertThat(encabezado.getText(), is("Crear Nuevo Usuario"));
  }
}