package org.ual.hmis.hmislovers;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class CrearbarTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    // Selector de navegador uniforme con el resto de la suite
    int browser = 0; // 0: firefox, 1: chrome
    boolean headless = true; // Forzado a true para ejecuciones en Jenkins (Xvfb)

    switch (browser) {
      case 0:  // Firefox
        org.openqa.selenium.firefox.FirefoxOptions firefoxOptions = new org.openqa.selenium.firefox.FirefoxOptions();
        if (headless) {
          firefoxOptions.addArguments("--headless");
        }
        driver = new org.openqa.selenium.firefox.FirefoxDriver(firefoxOptions);
        break;

      case 1: // Chrome
        org.openqa.selenium.chrome.ChromeOptions chromeOptions = new org.openqa.selenium.chrome.ChromeOptions();
        if (headless) {
          chromeOptions.addArguments("--headless=new");
        }
        chromeOptions.addArguments("--start-maximized"); 
        chromeOptions.addArguments("window-size=1920,1080");
        
        driver = new org.openqa.selenium.chrome.ChromeDriver(chromeOptions);
        break;

      default:
        fail("Please select a browser");
        break;
    }

    // Sincronización base implícita para evitar fallos de renderizado ligeros
    driver.manage().timeouts().implicitlyWait(java.time.Duration.ofSeconds(5));
    
    if (!headless) {
      driver.manage().window().maximize();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  @Test
  public void crearbar() {
    // GENERACIÓN DE NOMBRE ALEATORIO UNIQUE
    // Tomamos los primeros 6 caracteres de un UUID aleatorio para que no sea excesivamente largo
    String sufijoAleatorio = UUID.randomUUID().toString().substring(0, 6);
    String nombreBarAleatorio = "casa angel " + sufijoAleatorio;

    // 1. Ir a la página de login
    driver.get("https://calm-moss-09572aa03.7.azurestaticapps.net/login");
    driver.manage().window().maximize();
    
    // Instanciación del WebDriverWait para controlar las transiciones asíncronas
    WebDriverWait wait = new WebDriverWait(driver, java.time.Duration.ofSeconds(10));
    
    // 2. Realizar Login Seguro utilizando esperas explícitas
    WebElement userInput = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("login-username")));
    userInput.click();
    userInput.sendKeys("admin");
    
    driver.findElement(By.id("login-password")).sendKeys("1234");
    driver.findElement(By.cssSelector(".btn-auth-submit")).click();
    
    // 3. Flujo para añadir un nuevo bar
    // Esperar a que el botón de añadir bar esté activo tras la redirección post-login
    WebElement btnAddBar = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-add-bar")));
    btnAddBar.click();
    
    // Rellenar formulario del nuevo bar
    WebElement inputBarName = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("new-bar-name")));
    inputBarName.click();
    // MODIFICACIÓN: Enviamos el nombre aleatorio generado al principio
    inputBarName.sendKeys(nombreBarAleatorio);
    
    driver.findElement(By.id("new-bar-dir")).click();
    driver.findElement(By.id("new-bar-dir")).sendKeys("alli");
    
    // Guardar/Enviar el formulario del bar
    driver.findElement(By.cssSelector(".btn-submit-bar")).click();
    
    // 4. Verificación y Aserción final del bar creado
    // Si al crearse el nuevo bar se posiciona al final de la lista, forzamos una espera larga por si hay latencia
    WebDriverWait waitLargo = new WebDriverWait(driver, java.time.Duration.ofSeconds(20));
    
    // Buscamos dinámicamente la etiqueta h3 que contenga EXACTAMENTE el nombre aleatorio creado
    WebElement barCard = waitLargo.until(
        ExpectedConditions.elementToBeClickable(By.xpath("//h3[contains(text(), '" + nombreBarAleatorio + "')]"))
    );
    barCard.click();
    
    // Esperamos a que se abra el modal o vista de detalle social correspondiente
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".modal-header-social"))).click();
    
    // Capturamos el contenedor del título y verificamos que el texto guardado coincida de verdad
    WebElement txtTitle = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("div:nth-child(2) > h2")));
    
    // MODIFICACIÓN: Comparamos dinámicamente con la variable del nombre aleatorio
    assertThat(txtTitle.getText(), is(nombreBarAleatorio));
  }
}