package org.ual.hmis.hmislovers;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class CrearNuevoUsuarioCorrectoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    // Browser selector
    int browser = 0; // 0: firefox, 1: chrome
    boolean headless = false; // Cambiado a 'boolean' primitivo por buena práctica

    switch (browser) {
      case 0:  // Firefox
        // NOTA: Si usas Selenium 4.11 o superior, puedes comentar la línea de abajo 
        // y Selenium descargará el driver solo sin necesidad de la carpeta drivers/
        System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe");
        
        org.openqa.selenium.firefox.FirefoxOptions firefoxOptions = new org.openqa.selenium.firefox.FirefoxOptions();
        if (headless) {
          firefoxOptions.addArguments("--headless");
        }
        driver = new org.openqa.selenium.firefox.FirefoxDriver(firefoxOptions);
        break;

      case 1: // Chrome
        System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
        
        org.openqa.selenium.chrome.ChromeOptions chromeOptions = new org.openqa.selenium.chrome.ChromeOptions();
        if (headless) {
          chromeOptions.addArguments("--headless=new");
        }
        // Forzamos a Chrome a abrirse grande para que no falle ningún selector por temas de maquetación responsive
        chromeOptions.addArguments("--start-maximized"); 
        chromeOptions.addArguments("window-size=1920,1080");
        
        driver = new org.openqa.selenium.chrome.ChromeDriver(chromeOptions);
        break;

      default:
        fail("Please select a browser");
        break;
    }

    // Sincronización base para la suite
    driver.manage().timeouts().implicitlyWait(java.time.Duration.ofSeconds(5));
    
    // Garantizamos el maximizado físico de la ventana si el modo no es headless
    if (!headless) {
      driver.manage().window().maximize();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void crearNuevoUsuarioCorrecto() {
    // Generamos datos aleatorios únicos
    String randomSuffix = String.valueOf(System.currentTimeMillis()).substring(8);
    String nuevoUsuario = "juan" + randomSuffix;
    String nuevoEmail = "juan" + randomSuffix + "@gmail.ws";

    driver.get("http://localhost:5173/");
    driver.manage().window().maximize(); 
    
    WebDriverWait wait = new WebDriverWait(driver, java.time.Duration.ofSeconds(10));
    
    // ==========================================
    // PASO: INICIAR SESIÓN COMO ADMIN FIRST
    // ==========================================
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("login-username"))).sendKeys("admin");
    driver.findElement(By.id("login-password")).sendKeys("1234");
    driver.findElement(By.id("login-password")).sendKeys(Keys.ENTER);
    
    // ==========================================
    // PASO: IR AL PANEL DE ADMINISTRACIÓN
    // ==========================================
    WebElement btnAdmin = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-admin-header > .material-icons")));
    btnAdmin.click();
    
    WebElement btnAdd = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-admin-add")));
    btnAdd.click();
    
    // ==========================================
    // PASO: RELLENAR FORMULARIO
    // ==========================================
    WebElement inputUser = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("admin-new-username")));
    inputUser.click();
    inputUser.sendKeys(nuevoUsuario);
    
    driver.findElement(By.id("admin-new-email")).sendKeys(nuevoEmail);
    driver.findElement(By.id("admin-new-password")).sendKeys("awiofNÑWAOif");
    
    // Volvemos al clic físico sobre el botón de guardar por si el ENTER no enviaba el formulario
    WebElement btnSubmitBar = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-submit-bar")));
    btnSubmitBar.click();
    
    // ==========================================
    // PARCHE ANTIBLOQUEO: ¿HAY ALERTA DE ÉXITO?
    // ==========================================
    // Si tu app lanza un alert("Usuario creado") nativo tras guardar, hay que aceptarlo o la tabla no cargará
    try {
        WebDriverWait shortWait = new WebDriverWait(driver, java.time.Duration.ofSeconds(2));
        shortWait.until(ExpectedConditions.alertIsPresent());
        driver.switchTo().alert().accept();
    } catch (Exception e) {
        // Si no hay alerta nativa, continuamos de largo sin perder tiempo
    }
    
    // ==========================================
    // PASO: VALIDACIÓN EN LA LISTA
    // ==========================================
    // Modificamos el Localizador a uno más genérico y directo por texto visible en la pantalla
    WebElement celdaUsuario = wait.until(ExpectedConditions.visibilityOfElementLocated(
        By.xpath("//*[contains(text(), '" + nuevoUsuario + "')]")
    ));
    
    celdaUsuario.click();
    celdaUsuario.click();
    {
      Actions builder = new Actions(driver);
      builder.doubleClick(celdaUsuario).perform();
    }
    
    assertThat(celdaUsuario.getText(), is(nuevoUsuario));
  }
}