package org.ual.hmis.hmislovers;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class EliminarUsuarioCorrectamenteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    // Browser selector
    int browser = 0; // 0: firefox, 1: chrome
    boolean headless = true; // Cambiado a 'boolean' primitivo por buena práctica

    switch (browser) {
      case 0:  // Firefox
        
        //System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe");
        
        org.openqa.selenium.firefox.FirefoxOptions firefoxOptions = new org.openqa.selenium.firefox.FirefoxOptions();
        if (headless) {
          firefoxOptions.addArguments("--headless");
        }
        driver = new org.openqa.selenium.firefox.FirefoxDriver(firefoxOptions);
        break;

      case 1: // Chrome
        //System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
        
        org.openqa.selenium.chrome.ChromeOptions chromeOptions = new org.openqa.selenium.chrome.ChromeOptions();
        if (headless) {
          chromeOptions.addArguments("--headless=new");
        }
        // Forzamos a Chrome a abrirse grande para que no falle ningún selector por temas de maquetación responsive
        chromeOptions.addArguments("--start-maximized"); 
        chromeOptions.addArguments("window-size=1920,1080");
        
        driver = new org.openqa.selenium.chrome.ChromeDriver(chromeOptions);
        break;

      default:
        fail("Please select a browser");
        break;
    }

    // Sincronización base para la suite
    driver.manage().timeouts().implicitlyWait(java.time.Duration.ofSeconds(5));
    
    // Garantizamos el maximizado físico de la ventana si el modo no es headless
    if (!headless) {
      driver.manage().window().maximize();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void eliminarUsuarioCorrectamente() {
    // 1 | open | Vamos a la raíz primero para forzar la pantalla de login que vimos en tu captura
    driver.get("http://localhost:5173/");
    driver.manage().window().maximize(); // Asegura pantalla completa para evitar vistas responsive móviles
    
    WebDriverWait wait = new WebDriverWait(driver, java.time.Duration.ofSeconds(10));

    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("login-username"))).sendKeys("admin");
    driver.findElement(By.id("login-password")).sendKeys("1234");
    driver.findElement(By.cssSelector(".btn-auth-submit")).click();
    // ========================================================

    // 3 | click | Pulsamos el botón del panel de administración en la cabecera
    WebElement btnAdmin = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-admin-header > .material-icons")));
    btnAdmin.click();

    // 4 | click | Esperamos a que cargue la tabla y hacemos clic en el botón eliminar de la segunda fila
    WebElement btnDelete = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("tr:nth-child(2) .delete")));
    btnDelete.click();
    
    // CONTROL DE ALERTA: Si tu aplicación abre un modal de confirmación nativo del navegador, lo aceptamos:
    try {
        wait.until(ExpectedConditions.alertIsPresent());
        driver.switchTo().alert().accept();
    } catch (Exception e) {
        // Si no usa alerta nativa (sino un modal personalizado HTML), Selenium continuará sin pararse
    }

    // 5 | assertNotText | Esperamos a que la tabla se redibuje tras el borrado y confirmamos que la fila mutó
    WebElement textoValidar = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".font-bold")));
    assertThat(textoValidar.getText(), is(not("juanalberto")));
  }
}