package org.ual.hmis.hmislovers;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import java.util.*;

public class EliminarbarTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    // Selector de navegador uniforme para toda la suite de pruebas
    int browser = 0; // 0: firefox, 1: chrome
    boolean headless = true; // Forzado a true para evitar fallos de pantalla en Jenkins

    switch (browser) {
      case 0:  // Firefox
        org.openqa.selenium.firefox.FirefoxOptions firefoxOptions = new org.openqa.selenium.firefox.FirefoxOptions();
        if (headless) {
          firefoxOptions.addArguments("--headless");
        }
        driver = new org.openqa.selenium.firefox.FirefoxDriver(firefoxOptions);
        break;

      case 1: // Chrome
        org.openqa.selenium.chrome.ChromeOptions chromeOptions = new org.openqa.selenium.chrome.ChromeOptions();
        if (headless) {
          chromeOptions.addArguments("--headless=new");
        }
        chromeOptions.addArguments("--start-maximized"); 
        chromeOptions.addArguments("window-size=1920,1080");
        
        driver = new org.openqa.selenium.chrome.ChromeDriver(chromeOptions);
        break;

      default:
        fail("Please select a browser");
        break;
    }

    // Sincronización base implícita
    driver.manage().timeouts().implicitlyWait(java.time.Duration.ofSeconds(5));
    
    if (!headless) {
      driver.manage().window().maximize();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  @Test
  public void eliminarbar() {
    // GENERACIÓN DE UN NOMBRE ÚNICO ALEATORIO PARA ESTA PRUEBA
    String sufijoAleatorio = UUID.randomUUID().toString().substring(0, 6);
    String nombreBarAEliminar = "bar borrar " + sufijoAleatorio;

    // 1. Abrir la aplicación
    driver.get("https://calm-moss-09572aa03.7.azurestaticapps.net/");
    driver.manage().window().maximize();
    
    WebDriverWait wait = new WebDriverWait(driver, java.time.Duration.ofSeconds(10));
    WebDriverWait waitLargo = new WebDriverWait(driver, java.time.Duration.ofSeconds(25));
    
    // 2. LOGIN PREVIO (Necesario tanto para crear como para disponer del botón de borrado)
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("login-username"))).sendKeys("admin");
    driver.findElement(By.id("login-password")).sendKeys("1234");
    driver.findElement(By.cssSelector(".btn-auth-submit")).click();
    
    // 3. PASO PREVIO SEGURO: CREAR EL BAR QUE VAMOS A BORRAR
    WebElement btnAddBar = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-add-bar")));
    btnAddBar.click();
    
    WebElement inputBarName = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("new-bar-name")));
    inputBarName.click();
    inputBarName.sendKeys(nombreBarAEliminar);
    
    driver.findElement(By.id("new-bar-dir")).click();
    driver.findElement(By.id("new-bar-dir")).sendKeys("direccion temporal");
    
    driver.findElement(By.cssSelector(".btn-submit-bar")).click();

    // ==========================================
    // MEJORA DE ESTABILIZACIÓN ASÍNCRONA:
    // Esperamos a que el formulario/modal se cierre o deje de ser visible antes de buscar la tarjeta.
    wait.until(ExpectedConditions.invisibilityOfElementLocated(By.id("new-bar-name")));
    // ==========================================

    // 4. SELECCIONAR EL BAR DE FORMA DINÁMICA UTILIZANDO XPATH
    // Esperamos pacientemente a que la nueva tarjeta se pinte en la lista de fondo
    WebElement barCard = waitLargo.until(
        ExpectedConditions.visibilityOfElementLocated(By.xpath("//h3[contains(text(), '" + nombreBarAEliminar + "')]"))
    );
    
    // Hacemos scroll seguro hasta el elemento centrándolo verticalmente para evitar que quede oculto tras el header fijo
    js.executeScript("arguments[0].scrollIntoView({block: 'center'});", barCard);
    
    // Breve pausa para asegurar la estabilidad del scroll antes de la interacción
    try { Thread.sleep(500); } catch (Exception e) {}
    
    // Esperamos a que sea clickeable
    wait.until(ExpectedConditions.elementToBeClickable(barCard));
    
    // SOLUCIÓN AL FALLO DE INTERCEPCIÓN EN CHROME SIN ROMPER FIREFOX
    try {
        barCard.click();
    } catch (org.openqa.selenium.ElementClickInterceptedException e) {
        System.out.println("Clic convencional interceptado por .header-content en Chrome. Usando clic nativo por JavaScript...");
        js.executeScript("arguments[0].click();", barCard);
    }
    
    // 5. PULSAR EL BOTÓN ELIMINAR (.delete)
    WebElement btnDelete = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".delete")));
    btnDelete.click();
    
    // 6. GESTIÓN Y ASERCIÓN DE LA ALERTA DE CONFIRMACIÓN
    Alert alert = wait.until(ExpectedConditions.alertIsPresent());
    
    // Comprobamos que el texto de la alerta coincide exactamente con el esperado
    assertThat(alert.getText(), is("¿Estás seguro de que deseas eliminar este bar? También se borrarán sus reseñas."));
    
    // Aceptamos la alerta (Hacer clic en "Aceptar")
    alert.accept();

    // 7. COMPROBACIÓN EXTRA: Validar que el elemento ya no se encuentra visible en la UI
    waitLargo.until(ExpectedConditions.invisibilityOfElementLocated(By.xpath("//h3[contains(text(), '" + nombreBarAEliminar + "')]")));
  }
}