package org.ual.hmis.hmislovers;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class ListadoUsuariosCorrectoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    // Browser selector
    int browser = 1; // 0: firefox, 1: chrome
    boolean headless = true; 

    switch (browser) {
      case 0:  // Firefox
        org.openqa.selenium.firefox.FirefoxOptions firefoxOptions = new org.openqa.selenium.firefox.FirefoxOptions();
        if (headless) {
          firefoxOptions.addArguments("--headless");
        }
        driver = new org.openqa.selenium.firefox.FirefoxDriver(firefoxOptions);
        break;

      case 1: // Chrome
        org.openqa.selenium.chrome.ChromeOptions chromeOptions = new org.openqa.selenium.chrome.ChromeOptions();
        if (headless) {
          chromeOptions.addArguments("--headless=new");
        }
        chromeOptions.addArguments("--start-maximized"); 
        chromeOptions.addArguments("window-size=1920,1080");
        
        driver = new org.openqa.selenium.chrome.ChromeDriver(chromeOptions);
        break;

      default:
        fail("Please select a browser");
        break;
    }

    // Sincronización base para la suite
    driver.manage().timeouts().implicitlyWait(java.time.Duration.ofSeconds(5));
    
    if (!headless) {
      driver.manage().window().maximize();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  @Test
  public void listadoUsuariosCorrecto() {
    driver.get("https://calm-moss-09572aa03.7.azurestaticapps.net/");
    driver.manage().window().maximize();
    WebDriverWait wait = new WebDriverWait(driver, java.time.Duration.ofSeconds(10));
    
    // 1. LOGIN PREVIO OBLIGATORIO
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("login-username"))).sendKeys("admin");
    driver.findElement(By.id("login-password")).sendKeys("1234");
    driver.findElement(By.cssSelector(".btn-auth-submit")).click();
    
    // 2. IR AL PANEL DE ADMIN
    WebElement btnAdmin = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-admin-header")));
    btnAdmin.click();
   
    // 3. ESPERAR HASTA QUE LA TABLA DE USUARIOS SE RENDERICE Y EL ELEMENTO APAREZCA
    WebElement elementoNombre = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".font-bold")));
    
    // Acciones simuladas de Selenium IDE sobre el elemento seguro
    elementoNombre.click();
    elementoNombre.click();
    {
      Actions builder = new Actions(driver);
      builder.doubleClick(elementoNombre).perform();
    }
    
    // Aserción final del texto
    assertThat(elementoNombre.getText(), is("admin"));
  }
}