package org.ual.hmis.hmislovers;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginycierredesesinCasocorrectoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    // Browser selector
    int browser = 0; // 0: firefox, 1: chrome
    boolean headless = false; // Cambiado a 'boolean' primitivo por buena práctica

    switch (browser) {
      case 0:  // Firefox
        // NOTA: Si usas Selenium 4.11 o superior, puedes comentar la línea de abajo 
        // y Selenium descargará el driver solo sin necesidad de la carpeta drivers/
        System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe");
        
        org.openqa.selenium.firefox.FirefoxOptions firefoxOptions = new org.openqa.selenium.firefox.FirefoxOptions();
        if (headless) {
          firefoxOptions.addArguments("--headless");
        }
        driver = new org.openqa.selenium.firefox.FirefoxDriver(firefoxOptions);
        break;

      case 1: // Chrome
        System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
        
        org.openqa.selenium.chrome.ChromeOptions chromeOptions = new org.openqa.selenium.chrome.ChromeOptions();
        if (headless) {
          chromeOptions.addArguments("--headless=new");
        }
        // Forzamos a Chrome a abrirse grande para que no falle ningún selector por temas de maquetación responsive
        chromeOptions.addArguments("--start-maximized"); 
        chromeOptions.addArguments("window-size=1920,1080");
        
        driver = new org.openqa.selenium.chrome.ChromeDriver(chromeOptions);
        break;

      default:
        fail("Please select a browser");
        break;
    }

    // Sincronización base para la suite
    driver.manage().timeouts().implicitlyWait(java.time.Duration.ofSeconds(5));
    
    // Garantizamos el maximizado físico de la ventana si el modo no es headless
    if (!headless) {
      driver.manage().window().maximize();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginycierredesesinCasocorrecto() {
    // Test name: Login y cierre de sesión - Caso correcto
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:5173/");
    // 2 | setWindowSize | 736x815 | 
    driver.manage().window().setSize(new Dimension(736, 815));
    // 3 | click | id=login-username | 
    driver.findElement(By.id("login-username")).click();
    // 4 | type | id=login-username | admin
    driver.findElement(By.id("login-username")).sendKeys("admin");
    // 5 | type | id=login-password | 1234
    driver.findElement(By.id("login-password")).sendKeys("1234");
    // 6 | click | css=.btn-auth-submit | 
    driver.findElement(By.cssSelector(".btn-auth-submit")).click();
    // 7 | click | css=.feed-header | 
    driver.findElement(By.cssSelector(".feed-header")).click();
    // 8 | assertText | css=.title-group > p | Descubre cartas, comparte reseñas y opiniones de tapeo
    assertThat(driver.findElement(By.cssSelector(".title-group > p")).getText(), is("Descubre cartas, comparte reseñas y opiniones de tapeo"));
    // 9 | click | css=#logout-button-header > .material-icons | 
    driver.findElement(By.cssSelector("#logout-button-header > .material-icons")).click();
    // 10 | click | css=.login-card | 
    driver.findElement(By.cssSelector(".login-card")).click();
    // 11 | assertText | css=.form-group:nth-child(1) > label | Usuario o Correo:
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(1) > label")).getText(), is("Usuario o Correo:"));
  }
}
