package org.ual.hmis.hmislovers;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginCasoincorrectoCamposvacosTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    // Browser selector
    int browser = 1; // 0: firefox, 1: chrome
    boolean headless = true; // Cambiado a 'boolean' primitivo por buena práctica

    switch (browser) {
      case 0:  // Firefox
        
        //System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe");
        
        org.openqa.selenium.firefox.FirefoxOptions firefoxOptions = new org.openqa.selenium.firefox.FirefoxOptions();
        if (headless) {
          firefoxOptions.addArguments("--headless");
        }
        driver = new org.openqa.selenium.firefox.FirefoxDriver(firefoxOptions);
        break;

      case 1: // Chrome
        //System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
        
        org.openqa.selenium.chrome.ChromeOptions chromeOptions = new org.openqa.selenium.chrome.ChromeOptions();
        if (headless) {
          chromeOptions.addArguments("--headless=new");
        }
        // Forzamos a Chrome a abrirse grande para que no falle ningún selector por temas de maquetación responsive
        chromeOptions.addArguments("--start-maximized"); 
        chromeOptions.addArguments("window-size=1920,1080");
        
        driver = new org.openqa.selenium.chrome.ChromeDriver(chromeOptions);
        break;

      default:
        fail("Please select a browser");
        break;
    }

    // Sincronización base para la suite
    driver.manage().timeouts().implicitlyWait(java.time.Duration.ofSeconds(5));
    
    // Garantizamos el maximizado físico de la ventana si el modo no es headless
    if (!headless) {
      driver.manage().window().maximize();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginCasoincorrectoCamposvacos() {
    // Test name: Login - Caso incorrecto (Campos vacíos)
    // Step # | name | target | value
    // 1 | open | /login | 
    driver.get("https://calm-moss-09572aa03.7.azurestaticapps.net/");
    // 2 | setWindowSize | 736x815 | 
    driver.manage().window().setSize(new Dimension(736, 815));
    // 3 | click | css=.btn-auth-submit | 
    driver.findElement(By.cssSelector(".btn-auth-submit")).click();
    // 4 | click | css=.form-group:nth-child(1) > .field-error-msg | 
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .field-error-msg")).click();
    // 5 | assertText | css=.form-group:nth-child(1) > .field-error-msg | error\nEl usuario o correo electrónico es obligatorio.
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(1) > .field-error-msg")).getText(), is("error\nEl usuario o correo electrónico es obligatorio."));
    // 6 | click | css=.form-group:nth-child(2) > .field-error-msg | 
    driver.findElement(By.cssSelector(".form-group:nth-child(2) > .field-error-msg")).click();
    // 7 | assertText | css=.form-group:nth-child(2) > .field-error-msg | error\nLa contraseña es obligatoria.
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(2) > .field-error-msg")).getText(), is("error\nLa contraseña es obligatoria."));
  }
}
