package org.ual.hmis.hmislovers;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class ModificarbarTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    // Selector de navegador uniforme para toda la suite de pruebas
    int browser = 0; // 0: firefox, 1: chrome
    boolean headless = true; // Forzado a true para evitar fallos de pantalla en Jenkins

    switch (browser) {
      case 0:  // Firefox
        org.openqa.selenium.firefox.FirefoxOptions firefoxOptions = new org.openqa.selenium.firefox.FirefoxOptions();
        if (headless) {
          firefoxOptions.addArguments("--headless");
        }
        driver = new org.openqa.selenium.firefox.FirefoxDriver(firefoxOptions);
        break;

      case 1: // Chrome
        org.openqa.selenium.chrome.ChromeOptions chromeOptions = new org.openqa.selenium.chrome.ChromeOptions();
        if (headless) {
          chromeOptions.addArguments("--headless=new");
        }
        chromeOptions.addArguments("--start-maximized"); 
        chromeOptions.addArguments("window-size=1920,1080");
        
        driver = new org.openqa.selenium.chrome.ChromeDriver(chromeOptions);
        break;

      default:
        fail("Please select a browser");
        break;
    }

    // Sincronización base implícita
    driver.manage().timeouts().implicitlyWait(java.time.Duration.ofSeconds(5));
    
    if (!headless) {
      driver.manage().window().maximize();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  @Test
  public void modificarbar() {
    // GENERACIÓN DE NOMBRES ALEATORIOS ÚNICOS
    String sufijoAleatorio = UUID.randomUUID().toString().substring(0, 6);
    String nombreBarOriginal = "bar original " + sufijoAleatorio;
    String nombreBarModificado = "casa angel si " + sufijoAleatorio;

    // 1. Abrir la aplicación
    driver.get("https://calm-moss-09572aa03.7.azurestaticapps.net/");
    driver.manage().window().maximize();
    
    // Esperas estándares y largas para absorber latencias de red
    WebDriverWait wait = new WebDriverWait(driver, java.time.Duration.ofSeconds(10));
    WebDriverWait waitLargoBares = new WebDriverWait(driver, java.time.Duration.ofSeconds(25));
    
    // 2. LOGIN PREVIO (Requisito para poder gestionar elementos de administración)
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("login-username"))).sendKeys("admin");
    driver.findElement(By.id("login-password")).sendKeys("1234");
    driver.findElement(By.cssSelector(".btn-auth-submit")).click();
    
    // 3. CREACIÓN PREVIA DEL BAR QUE SE VA A MODIFICAR
    WebElement btnAddBar = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-add-bar")));
    btnAddBar.click();
    
    WebElement inputBarNameNuevo = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("new-bar-name")));
    inputBarNameNuevo.click();
    inputBarNameNuevo.sendKeys(nombreBarOriginal);
    
    driver.findElement(By.id("new-bar-dir")).click();
    driver.findElement(By.id("new-bar-dir")).sendKeys("alli");
    
    driver.findElement(By.cssSelector(".btn-submit-bar")).click();
    
    // Esperar a que el modal de creación se cierre antes de buscar la tarjeta
    wait.until(ExpectedConditions.invisibilityOfElementLocated(By.id("new-bar-name")));
    wait.until(ExpectedConditions.invisibilityOfElementLocated(By.cssSelector(".btn-submit-bar")));
    
    // 4. SELECCIONAR EL BAR CREADO USANDO XPATH DINÁMICO
    WebElement barCard = waitLargoBares.until(
        ExpectedConditions.elementToBeClickable(By.xpath("//h3[contains(text(), '" + nombreBarOriginal + "')]"))
    );
    barCard.click();
    
    // 5. PULSAR EL BOTÓN EDITAR (.edit)
    WebElement btnEdit = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".edit")));
    btnEdit.click();
    
    // 6. MODIFICAR ATRIBUTOS DEL FORMULARIO 
    WebElement inputBarDir = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("new-bar-dir")));
    inputBarDir.click();
    inputBarDir.clear(); // Limpieza robusta para Jenkins headless
    inputBarDir.sendKeys("alli o no");
    
    WebElement inputBarName = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("new-bar-name")));
    inputBarName.click();
    inputBarName.clear(); // Limpieza robusta para Jenkins headless
    inputBarName.sendKeys(nombreBarModificado);
    
    // 7. GUARDAR CAMBIOS
    WebElement btnSubmit = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-submit-bar")));
    btnSubmit.click();
    
    // ESPERA DE SEGURIDAD A: Esperamos a que el formulario de edición desaparezca (lo que confirma el guardado)
    wait.until(ExpectedConditions.invisibilityOfElementLocated(By.cssSelector(".btn-submit-bar")));
    
    // ESPERA DE SEGURIDAD B: Pausa de 500ms para que la animación CSS del overlay termine de desvanecerse
    try {
        Thread.sleep(500);
    } catch (InterruptedException e) {
        Thread.currentThread().interrupt();
    }
    
    // 8. CERRAR DETALLE (cerramos el detalle de forma segura para volver a la lista de bares)
    WebElement btnCloseModal = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-close-modal > .material-icons")));
    btnCloseModal.click();
    
    // Volvemos a hacer clic en el bar usando el NUEVO nombre modificado para comprobar la persistencia de la vista detallada
    WebElement barCardUpdated = waitLargoBares.until(
        ExpectedConditions.elementToBeClickable(By.xpath("//h3[contains(text(), '" + nombreBarModificado + "')]"))
    );
    barCardUpdated.click();
    
    // Esperamos a que la etiqueta del nuevo título sea visible en el panel social/detalle y realizamos el Assert final
    WebElement txtTitle = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("div:nth-child(2) > h2")));
    
    assertThat(txtTitle.getText(), is(nombreBarModificado));
  }
}