package org.ual.hmis.hmislovers;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class ModificarUsuariosIncorrectamenteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    // Browser selector
    int browser = 1; // 0: firefox, 1: chrome
    boolean headless = true; 

    switch (browser) {
      case 0:  // Firefox
        org.openqa.selenium.firefox.FirefoxOptions firefoxOptions = new org.openqa.selenium.firefox.FirefoxOptions();
        if (headless) {
          firefoxOptions.addArguments("--headless");
        }
        driver = new org.openqa.selenium.firefox.FirefoxDriver(firefoxOptions);
        break;

      case 1: // Chrome
        org.openqa.selenium.chrome.ChromeOptions chromeOptions = new org.openqa.selenium.chrome.ChromeOptions();
        if (headless) {
          chromeOptions.addArguments("--headless=new");
        }
        chromeOptions.addArguments("--start-maximized"); 
        chromeOptions.addArguments("window-size=1920,1080");
        
        // INSTANCIACIÓN CORRECTA: Primero se crea el driver
        driver = new org.openqa.selenium.chrome.ChromeDriver(chromeOptions);
        break;

      default:
        fail("Please select a browser");
        break;
    }

    // CONFIGURACIÓN POSTERIOR: Ya no dará NullPointerException porque 'driver' nunca es nulo aquí
    driver.manage().timeouts().implicitlyWait(java.time.Duration.ofSeconds(5));
    
    if (!headless) {
      driver.manage().window().maximize();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  @Test
  public void modificarUsuariosIncorrectamente() {
    driver.get("https://calm-moss-09572aa03.7.azurestaticapps.net/");
    driver.manage().window().maximize();
    WebDriverWait wait = new WebDriverWait(driver, java.time.Duration.ofSeconds(10));
    
    // 1. LOGIN
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("login-username"))).sendKeys("admin");
    driver.findElement(By.id("login-password")).sendKeys("1234");
    driver.findElement(By.cssSelector(".btn-auth-submit")).click();
    
    // 2. PANEL DE ADMINISTRACIÓN
    WebElement btnAdmin = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-admin-header")));
    btnAdmin.click();
    
    // 3. ESPERAR A QUE EL BOTÓN DE EDICIÓN (.edit > .material-icons) SEA VERDADERAMENTE CLICKEABLE
    WebElement btnEdit = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".edit > .material-icons")));
    btnEdit.click();
    
    // 4. CONTINUACIÓN DEL FLUJO DEL TEST (Campos erróneos o cancelación)
    // Añade aquí los inputs erróneos y asserts finales que requiera tu caso de uso incorrecto
  }
}