package org.ual.hmis.hmislovers;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class ModificarUsuarioCorrectamenteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    // Browser selector
    int browser = 0; // 0: firefox, 1: chrome
    boolean headless = true; // Cambiado a 'boolean' primitivo por buena práctica

    switch (browser) {
      case 0:  // Firefox
       
        //System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe");
        
        org.openqa.selenium.firefox.FirefoxOptions firefoxOptions = new org.openqa.selenium.firefox.FirefoxOptions();
        if (headless) {
          firefoxOptions.addArguments("--headless");
        }
        driver = new org.openqa.selenium.firefox.FirefoxDriver(firefoxOptions);
        break;

      case 1: // Chrome
        //System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
        
        org.openqa.selenium.chrome.ChromeOptions chromeOptions = new org.openqa.selenium.chrome.ChromeOptions();
        if (headless) {
          chromeOptions.addArguments("--headless=new");
        }
        // Forzamos a Chrome a abrirse grande para que no falle ningún selector por temas de maquetación responsive
        chromeOptions.addArguments("--start-maximized"); 
        chromeOptions.addArguments("window-size=1920,1080");
        
        driver = new org.openqa.selenium.chrome.ChromeDriver(chromeOptions);
        break;

      default:
        fail("Please select a browser");
        break;
    }

    // Sincronización base para la suite
    driver.manage().timeouts().implicitlyWait(java.time.Duration.ofSeconds(5));
    
    // Garantizamos el maximizado físico de la ventana si el modo no es headless
    if (!headless) {
      driver.manage().window().maximize();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void modificarUsuarioCorrectamente() {
    // 1 | open | Vamos a la raíz de la aplicación local
    driver.get("https://calm-moss-09572aa03.7.azurestaticapps.net/");
    driver.manage().window().maximize();
    WebDriverWait wait = new WebDriverWait(driver, java.time.Duration.ofSeconds(10));
    
    // 1. LOGIN PREVIO OBLIGATORIO
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("login-username"))).sendKeys("admin");
    driver.findElement(By.id("login-password")).sendKeys("1234");
    driver.findElement(By.cssSelector(".btn-auth-submit")).click();
    
    // 2. IR AL PANEL DE ADMIN
    WebElement btnAdmin = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-admin-header")));
    btnAdmin.click();

    // 4 | click | Esperamos a que la lista cargue y hacemos clic en el botón de edición
    WebElement btnEdit = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".edit")));
    btnEdit.click();

    // 5 | click | Esperamos a que el formulario flotante o vista de edición muestre el campo
    WebElement inputLevel = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("admin-edit-level")));
    inputLevel.click();

    // 6 | type | Limpiamos el valor por defecto e insertamos el nuevo nivel "12"
    inputLevel.clear(); 
    inputLevel.sendKeys("12");

    // 7 | click | Guardamos los cambios pulsando el botón de envío
    driver.findElement(By.cssSelector(".btn-submit-bar")).click();
    
    // Esperamos a que los elementos interceptores (label) desaparezcan
    wait.until(ExpectedConditions.invisibilityOfAllElements(
        driver.findElements(By.cssSelector("label"))
    ));
    
    // Luego esperamos a que el elemento sea completamente clickeable
    WebElement levelPill = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".level-pill")));

    // 8 y 9 | click | Hacemos las interacciones sobre la píldora de nivel actualizada
    levelPill.click();
    levelPill.click();

    // 10 | doubleClick | Lanzamos la acción de doble clic requerida
    {
      Actions builder = new Actions(driver);
      builder.doubleClick(levelPill).perform();
    }

    // 11 | assertText | Confirmamos que el texto reflejado en pantalla sea el esperado
    assertThat(levelPill.getText(), is("Lvl 12"));
  }
}