package org.ual.hmis.hmislovers;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class ModificarbarTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    int browser = 0; // 0: firefox, 1: chrome
    boolean headless = true;

    switch (browser) {
      case 0:  // Firefox
        org.openqa.selenium.firefox.FirefoxOptions firefoxOptions = new org.openqa.selenium.firefox.FirefoxOptions();
        if (headless) {
          firefoxOptions.addArguments("--headless");
        }
        driver = new org.openqa.selenium.firefox.FirefoxDriver(firefoxOptions);
        break;

      case 1: // Chrome
        org.openqa.selenium.chrome.ChromeOptions chromeOptions = new org.openqa.selenium.chrome.ChromeOptions();
        if (headless) {
          chromeOptions.addArguments("--headless=new");
        }
        chromeOptions.addArguments("--start-maximized"); 
        chromeOptions.addArguments("window-size=1920,1080");
        
        driver = new org.openqa.selenium.chrome.ChromeDriver(chromeOptions);
        break;

      default:
        fail("Please select a browser");
        break;
    }

    driver.manage().timeouts().implicitlyWait(java.time.Duration.ofSeconds(5));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  @Test
  public void modificarbar() {
    // COOL-DOWN PARA AZURE: Evitamos saturar el servidor al inicio de la prueba
    try { Thread.sleep(4000); } catch (Exception e) {}

    String sufijoAleatorio = UUID.randomUUID().toString().substring(0, 6);
    String nombreBarOriginal = "bar original " + sufijoAleatorio;
    String nombreBarModificado = "casa angel si " + sufijoAleatorio;

    driver.get("https://calm-moss-09572aa03.7.azurestaticapps.net/");
    driver.manage().window().maximize();
    
    WebDriverWait wait = new WebDriverWait(driver, java.time.Duration.ofSeconds(15));
    WebDriverWait waitLargoBares = new WebDriverWait(driver, java.time.Duration.ofSeconds(45));
    
    // Login previo
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("login-username"))).sendKeys("admin");
    driver.findElement(By.id("login-password")).sendKeys("1234");
    driver.findElement(By.cssSelector(".btn-auth-submit")).click();
    
    // Crear bar
    WebElement btnAddBar = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-add-bar")));
    btnAddBar.click();
    
    WebElement inputBarNameNuevo = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("new-bar-name")));
    inputBarNameNuevo.click();
    inputBarNameNuevo.sendKeys(nombreBarOriginal);
    
    driver.findElement(By.id("new-bar-dir")).click();
    driver.findElement(By.id("new-bar-dir")).sendKeys("direccion original 123");
    driver.findElement(By.cssSelector(".btn-submit-bar")).click();
    
    wait.until(ExpectedConditions.invisibilityOfElementLocated(By.id("new-bar-name")));
    wait.until(ExpectedConditions.invisibilityOfElementLocated(By.cssSelector(".btn-submit-bar")));
    
    // Seleccionar bar
    WebElement barCard = waitLargoBares.until(
        ExpectedConditions.elementToBeClickable(By.xpath("//h3[contains(., '" + nombreBarOriginal + "')]"))
    );
    barCard.click();
    
    // Pulsar editar
    WebElement btnEdit = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".edit")));
    btnEdit.click();
    
    // Modificar datos
    WebElement inputBarDir = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("new-bar-dir")));
    inputBarDir.click();
    inputBarDir.clear(); 
    inputBarDir.sendKeys("alli o no");
    
    WebElement inputBarName = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("new-bar-name")));
    inputBarName.click();
    inputBarName.clear(); 
    inputBarName.sendKeys(nombreBarModificado);
    
    // Guardar cambios
    WebElement btnSubmit = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-submit-bar")));
    btnSubmit.click();
    
    wait.until(ExpectedConditions.invisibilityOfElementLocated(By.cssSelector(".btn-submit-bar")));
    
    // Cerrar vista detalle para volver a la lista principal
    WebElement btnCloseModal = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-close-modal > .material-icons")));
    btnCloseModal.click();
    
    // Seleccionar usando el NUEVO nombre modificado
    WebElement barCardAgain = waitLargoBares.until(
        ExpectedConditions.elementToBeClickable(By.xpath("//h3[contains(., '" + nombreBarModificado + "')]"))
    );
    barCardAgain.click();
    
    // Validar visualización y aserción correcta del nuevo nombre
    WebElement txtTitle = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("div:nth-child(2) > h2")));
    assertTrue(txtTitle.isDisplayed());
    assertThat(txtTitle.getText(), is(nombreBarModificado));
  }
}