package org.ual.hmis.hmislovers;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ModificarUsuariosIncorrectamenteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    // Browser selector
    int browser = 0; // 0: firefox, 1: chrome
    boolean headless = true; // Cambiado a 'boolean' primitivo por buena práctica

    switch (browser) {
      case 0:  // Firefox
        
        //System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe");
        
        org.openqa.selenium.firefox.FirefoxOptions firefoxOptions = new org.openqa.selenium.firefox.FirefoxOptions();
        if (headless) {
          firefoxOptions.addArguments("--headless");
        }
        driver = new org.openqa.selenium.firefox.FirefoxDriver(firefoxOptions);
        break;

      case 1: // Chrome
        //System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
        
        org.openqa.selenium.chrome.ChromeOptions chromeOptions = new org.openqa.selenium.chrome.ChromeOptions();
        if (headless) {
          chromeOptions.addArguments("--headless=new");
        }
        // Forzamos a Chrome a abrirse grande para que no falle ningún selector por temas de maquetación responsive
        chromeOptions.addArguments("--start-maximized"); 
        chromeOptions.addArguments("window-size=1920,1080");
        
        driver = new org.openqa.selenium.chrome.ChromeDriver(chromeOptions);
        break;

      default:
        fail("Please select a browser");
        break;
    }

    // Sincronización base para la suite
    driver.manage().timeouts().implicitlyWait(java.time.Duration.ofSeconds(5));
    
    // Garantizamos el maximizado físico de la ventana si el modo no es headless
    if (!headless) {
      driver.manage().window().maximize();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void modificarUsuariosIncorrectamente() {
    // Test name: ModificarUsuariosIncorrectamente
    // Step # | name | target | value
    // 1 | open | /admin | 
	  driver.get("http://localhost:5173/");
	    driver.manage().window().maximize();
	    WebDriverWait wait = new WebDriverWait(driver, java.time.Duration.ofSeconds(10));
	    
	    // 1. LOGIN PREVIO OBLIGATORIO
	    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("login-username"))).sendKeys("admin");
	    driver.findElement(By.id("login-password")).sendKeys("1234");
	    driver.findElement(By.cssSelector(".btn-auth-submit")).click();
	    
	    // 2. IR AL PANEL DE ADMIN
	    WebElement btnAdmin = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-admin-header")));
	    btnAdmin.click();
    // 4 | click | css=.edit > .material-icons | 
    driver.findElement(By.cssSelector(".edit > .material-icons")).click();
    // 5 | click | id=admin-edit-username | 
    driver.findElement(By.id("admin-edit-username")).click();
    // 7 | click | css=.btn-submit-bar | 
    driver.findElement(By.cssSelector(".btn-submit-bar")).click();
    // 8 | click | css=.font-bold | 
    driver.findElement(By.cssSelector(".font-bold")).click();
    // 9 | click | css=.font-bold | 
    driver.findElement(By.cssSelector(".font-bold")).click();
    // 10 | doubleClick | css=.font-bold | 
    {
      WebElement element = driver.findElement(By.cssSelector(".font-bold"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 11 | assertText | css=.font-bold | admin
    assertThat(driver.findElement(By.cssSelector(".font-bold")).getText(), is("admin"));
  }
}
