package org.ual.hmis.hmislovers;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.containsString;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class RegistroCasoincorrectoCamposvacosTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    // Browser selector
    int browser = 0; // 0: firefox, 1: chrome
    boolean headless = true; // Cambiado a 'boolean' primitivo por buena práctica

    switch (browser) {
      case 0:  // Firefox
       
        //System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe");
        
        org.openqa.selenium.firefox.FirefoxOptions firefoxOptions = new org.openqa.selenium.firefox.FirefoxOptions();
        if (headless) {
          firefoxOptions.addArguments("--headless");
        }
        driver = new org.openqa.selenium.firefox.FirefoxDriver(firefoxOptions);
        break;

      case 1: // Chrome
        //System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
        
        org.openqa.selenium.chrome.ChromeOptions chromeOptions = new org.openqa.selenium.chrome.ChromeOptions();
        if (headless) {
          chromeOptions.addArguments("--headless=new");
        }
        // Forzamos a Chrome a abrirse grande para que no falle ningún selector por temas de maquetación responsive
        chromeOptions.addArguments("--start-maximized"); 
        chromeOptions.addArguments("window-size=1920,1080");
        
        driver = new org.openqa.selenium.chrome.ChromeDriver(chromeOptions);
        break;

      default:
        fail("Please select a browser");
        break;
    }

    // Sincronización base para la suite
    driver.manage().timeouts().implicitlyWait(java.time.Duration.ofSeconds(5));
    
    // Garantizamos el maximizado físico de la ventana si el modo no es headless
    if (!headless) {
      driver.manage().window().maximize();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void registroCasoincorrectoCamposvacos() {
    // 1 | open | Ir a la aplicación
    driver.get("https://calm-moss-09572aa03.7.azurestaticapps.net/");
    driver.manage().window().maximize();
    
    WebDriverWait wait = new WebDriverWait(driver, java.time.Duration.ofSeconds(10));

    // 3 | Ir a la vista de registro
    wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Regístrate aquí"))).click();

    // 4 | Esperar al campo de username e interactuar con él
    WebElement inputUser = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("register-username")));
    
    // 5 | Pulsamos ENTER en el input vacío para disparar las validaciones nativas de la app
    inputUser.sendKeys(Keys.ENTER);

    // ==========================================
    // VALIDACIÓN DE ERRORES POR CAMPO
    // ==========================================
    
    // Error 1: Nombre de usuario
    WebElement errorUsuario = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".form-group:nth-child(1) > .field-error-msg")));
    assertThat(errorUsuario.getText(), containsString("El nombre de usuario es obligatorio."));

    // Error 2: Correo electrónico
    WebElement errorEmail = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".form-group:nth-child(2) > .field-error-msg")));
    assertThat(errorEmail.getText(), containsString("El correo electrónico es obligatorio."));

    // Error 3: Contraseña
    WebElement errorPassword = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".form-group:nth-child(3) > .field-error-msg")));
    assertThat(errorPassword.getText(), containsString("La contraseña es obligatoria."));

    // NOTA: Se elimina la validación de ".auth-error-message" (errorGlobal) 
    // debido a que la interfaz de usuario gestiona los mensajes únicamente de forma localizada por campo.
  }
}