package org.ual.hmis.hmislovers;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistroCasoincorrectoNombreenusoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    // Browser selector
    int browser = 0; // 0: firefox, 1: chrome
    boolean headless = true; // Cambiado a 'boolean' primitivo por buena práctica

    switch (browser) {
      case 0:  // Firefox
        
        //System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe");
        
        org.openqa.selenium.firefox.FirefoxOptions firefoxOptions = new org.openqa.selenium.firefox.FirefoxOptions();
        if (headless) {
          firefoxOptions.addArguments("--headless");
        }
        driver = new org.openqa.selenium.firefox.FirefoxDriver(firefoxOptions);
        break;

      case 1: // Chrome
        //System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
        
        org.openqa.selenium.chrome.ChromeOptions chromeOptions = new org.openqa.selenium.chrome.ChromeOptions();
        if (headless) {
          chromeOptions.addArguments("--headless=new");
        }
        // Forzamos a Chrome a abrirse grande para que no falle ningún selector por temas de maquetación responsive
        chromeOptions.addArguments("--start-maximized"); 
        chromeOptions.addArguments("window-size=1920,1080");
        
        driver = new org.openqa.selenium.chrome.ChromeDriver(chromeOptions);
        break;

      default:
        fail("Please select a browser");
        break;
    }

    // Sincronización base para la suite
    driver.manage().timeouts().implicitlyWait(java.time.Duration.ofSeconds(5));
    
    // Garantizamos el maximizado físico de la ventana si el modo no es headless
    if (!headless) {
      driver.manage().window().maximize();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registroCasoincorrectoNombreenuso() {
    // Test name: Registro - Caso incorrecto (Nombre en uso)
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:5173/");
    // 2 | setWindowSize | 736x815 | 
    driver.manage().window().setSize(new Dimension(736, 815));
    // 3 | click | linkText=Regístrate aquí | 
    driver.findElement(By.linkText("Regístrate aquí")).click();
    // 4 | click | id=register-username | 
    driver.findElement(By.id("register-username")).click();
    // 5 | type | id=register-username | admin
    driver.findElement(By.id("register-username")).sendKeys("admin");
    // 6 | type | id=register-email | a@a.com
    driver.findElement(By.id("register-email")).sendKeys("a@a.com");
    // 7 | type | id=register-password | hola
    driver.findElement(By.id("register-password")).sendKeys("hola");
    // 8 | click | css=.btn-auth-submit | 
    driver.findElement(By.cssSelector(".btn-auth-submit")).click();
    // 9 | mouseOver | css=.btn-auth-submit | 
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-auth-submit"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 10 | mouseOut | css=.btn-auth-submit | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 11 | click | css=.field-error-msg | 
    driver.findElement(By.cssSelector(".field-error-msg")).click();
    // 12 | assertText | css=.field-error-msg | error\nEl nombre de usuario ya existe
    assertThat(driver.findElement(By.cssSelector(".field-error-msg")).getText(), is("error\nEl nombre de usuario ya existe"));
  }
}
